version: '3'
services:
  app:
    build: .
    ports:
      - "8009:8000"
    volumes:
      - .:/app
    environment:
      - DB_HOST=arquigrafia
    env_file: .env
    working_dir: /app
    command: bash -c 'php artisan migrate --database arquigrafia && php artisan serve --host 0.0.0.0'
    depends_on:
      - db
    links:
      - db
  db:
    image: "mysql:5.7"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD= 1
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=arquigrafia
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
    command: --init-file /app/data/application/init.sql
    volumes:
      - ./data/application:/app/data/application/
    ports:
      - "3307:3306"
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8090:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ''
